name: Build
run-name: Running testutils build.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@main

    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v5
      with:
        node-version: ${{ vars.NODE_VERSION }}
        registry-url: 'https://npm.pkg.github.com'

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@main
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        # todo - change this so we are less restrictive on package-lock changes
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - run: npm ci

    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      name: List the state of node modules
      continue-on-error: true
      run: npm list

    - run: npm run test
    - run: npm run build:dist

    - name: Run all checks at end on all other branches
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/prod'
      run: |
        npm publish --dry-run
  